spring.application.name=billing-job

# Spring Boot will autoconfigure a JDBC DataSource bean in the application context
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
